name: lurp
description: "A Flutter package to display interactive read-only polls (Selection, Slider, and Rating) and thought posts integrated with the Lurp ecosystem."
version: 0.0.2
homepage: https://www.lurp.it/en
repository: https://github.com/wopuff/lurp-widget
issue_tracker: https://github.com/wopuff/lurp-widget/issues

environment:
  sdk: ^3.11.5
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  logger: ^2.7.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

linter:
  rules:
    public_member_api_docs: true
    