name: lurp
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.lurp.it/en

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  logger: ^2.7.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
